#!/usr/bin/env bash
set -ex

# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.
jupyter nbconvert \
	--to 'html' \
	--ExecutePreprocessor.allow_errors=True \
	--ExecutePreprocessor.timeout=-1 \
	--FilesWriter.build_directory=../results \
	--execute feature_analysis.ipynb

# The previous version of this file was commented-out and follows below:
#
# jupyter nbconvert \
# 	--to 'html' \
# 	--ExecutePreprocessor.allow_errors=True \
# 	--ExecutePreprocessor.timeout=-1 \
# 	--FilesWriter.build_directory=../results \
# 	--execute 'statistic analysis.ipynb'
# 
# # The previous version of this file was commented-out and follows below:
# #
# # jupyter nbconvert \
# # 	--to 'html' \
# # 	--ExecutePreprocessor.allow_errors=True \
# # 	--ExecutePreprocessor.timeout=-1 \
# # 	--FilesWriter.build_directory=../results \
# # 	--execute feature_analysis.ipynb
# # 
# # # The previous version of this file was commented-out and follows below:
# # #
# # # jupyter nbconvert \
# # # 	--to 'html' \
# # # 	--ExecutePreprocessor.allow_errors=True \
# # # 	--ExecutePreprocessor.timeout=-1 \
# # # 	--FilesWriter.build_directory=../results \
# # # 	--execute feature_analysis.ipynb
# # # 
# # # # The previous version of this file was commented-out and follows below:
# # # #
# # # # jupyter nbconvert \
# # # # 	--to 'html' \
# # # # 	--ExecutePreprocessor.allow_errors=True \
# # # # 	--ExecutePreprocessor.timeout=-1 \
# # # # 	--FilesWriter.build_directory=../results \
# # # # 	--execute feature_analysis.ipynb
# # # # 
# # # # # The previous version of this file was commented-out and follows below:
# # # # #
# # # # # jupyter nbconvert \
# # # # # 	--to 'html' \
# # # # # 	--ExecutePreprocessor.allow_errors=True \
# # # # # 	--ExecutePreprocessor.timeout=-1 \
# # # # # 	--FilesWriter.build_directory=../results \
# # # # # 	--execute feature_analysis.ipynb
# # # # # 
# # # # # # The previous version of this file was commented-out and follows below:
# # # # # #
# # # # # # jupyter nbconvert \
# # # # # # 	--to 'html' \
# # # # # # 	--ExecutePreprocessor.allow_errors=True \
# # # # # # 	--ExecutePreprocessor.timeout=-1 \
# # # # # # 	--FilesWriter.build_directory=../results \
# # # # # # 	--execute feature_analysis.ipynb
# # # # # # 
# # # # # # # The previous version of this file was commented-out and follows below:
# # # # # # #
# # # # # # # jupyter nbconvert \
# # # # # # # 	--to 'html' \
# # # # # # # 	--ExecutePreprocessor.allow_errors=True \
# # # # # # # 	--ExecutePreprocessor.timeout=-1 \
# # # # # # # 	--FilesWriter.build_directory=../results \
# # # # # # # 	--execute feature_analysis.ipynb
# # # # # # # 
# # # # # # # # The previous version of this file was commented-out and follows below:
# # # # # # # #
# # # # # # # # Rscript delong_test.R "$@"
# # # # # # # # 
# # # # # # # # # The previous version of this file was commented-out and follows below:
# # # # # # # # #
# # # # # # # # # jupyter nbconvert \
# # # # # # # # # 	--to 'html' \
# # # # # # # # # 	--ExecutePreprocessor.allow_errors=True \
# # # # # # # # # 	--ExecutePreprocessor.timeout=-1 \
# # # # # # # # # 	--FilesWriter.build_directory=../results \
# # # # # # # # # 	--execute 'statistic analysis.ipynb'
# # # # # # # # # 
# # # # # # # # 
# # # # # # # 
# # # # # # 
# # # # # 
# # # # 
# # # 
# # 
# 
